build:
  npm_install:
    environment:
      http_proxy: http://10.20.4.15:3128/
    image: node
    commands:
    - npm install
  test:
    image: node
    commands:
    - npm run test-single-run
  build:
    image: node
    commands:
      - 
  package:
    image: alpine
    commands:
    - tar cf package-$$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER.tar index.html bundle.js
    - gzip package-$$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER.tar
